sudo: false

language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export JOBS=max

os:
  - osx
  - linux

node_js:
  - 6
  - 8
  - 9
  - 10
